syntax = "proto3";

package market.v1;

service MarketService {
  rpc GetPrice(PriceRequest) returns (PriceResponse);
  rpc SubscribePrices(SubscribeRequest) returns (stream PriceUpdate);
  rpc TradeStream(stream TradeRequest) returns (stream TradeEvent);
}

message PriceRequest { string symbol = 1; }

message PriceResponse {
  string symbol = 1;
  double price = 2;
  uint64 timestamp = 3;
}

message SubscribeRequest { /*repeated */ string symbol = 1; }

message PriceUpdate {
  string symbol = 1;
  double price = 2;
  uint64 timestamp = 3;
}

enum TradeRequestType {
  UNDEFINED = 0;
  NEW_ORDER = 1;
  CANCEL_ORDER = 2;
}

message TradeRequest {
  TradeRequestType type = 1;

  string symbol = 2;
  double price = 3;
  uint32 quantity = 4;

  bool is_buy = 5;
  bool is_market_order = 6;

  uint32 clientId = 7;
  uint64 orderId = 8;

}

message TradeEvent {
  string symbol = 1;
  double price = 2;
  string status = 3;
  uint32 quantity = 4;
  uint32 clientId = 5;
  uint64 orderId = 6;
  bool is_fully_filled = 7;
}
