name: C++ Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}/ci-base:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build -G Ninja

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build -j$(nproc)

    # - name: Check crush on startup
    #   run: |
    #     timeout 3s ${{github.workspace}}/build/server/market_server || [ $? eq 124 ]